### ISSUE TITLE
`compare_models` bug

### ISSUE THREAD

**Issue by marcela-gouvea** [cgalelli/gammapy_SyLC#4]
`compare_models` fails similarly to the issue described in #2: arguments are passed to `pdf_fit` in the wrong order (positional call).

### Traceback

```python
Traceback (most recent call last):
  File ".../pdf_fit.py", line 636, in <module>
    results = run_tests(
  File ".../pdf_fit.py", line 487, in run_tests
    fit_stats_g, p_g = compare_models(
  File ".../site-packages/gammapy_SyLC/fitting.py", line 387, in compare_models
    fit_stats = pdf_fit(
  File ".../site-packages/gammapy_SyLC/fitting.py", line 206, in pdf_fit
    list(pdf_initial.values()),
AttributeError: 'function' object has no attribute 'values'
```

Expected pdf_fit signature:

```
 pdf_fit(
        flux,
        psd,
        psd_params,
        pdf,
        pdf_initial,
        obs_times,
        nsims=10000,
        flux_error=None,
        output_type="value",
        **kwargs,
)

```
Actual call inside `compare_models`

```
pdf_fit(
        flux,
        obs_times,
        psd,
        psd_params,
        pdf_test,
        pdf_initial,
        nsims=nsims*5,
        flux_error=flux_error,
        output_type="full",
        **kwargs, )
```
This positional call maps the arguments incorrectly (obs_times → psd, psd → psd_params, etc.), which leads to pdf_initial being interpreted as a function instead of a dictionary, hence the .values() error.

I will propose a PR to fix this using explicit keyword arguments (same approach as PR #3).
